// ============================================
// DWS TEMPLATES (110 Daily Work Standard Tasks)
// ============================================
// Extracted from ai-hq-task-assignment/src/data/mockData.ts

import { TaskTemplate } from '../types';

export const dwsTemplates: TaskTemplate[] = [
  // POS Operations (18 tasks)
  {
    id: 1,
    code: '1.1.1',
    title: 'Morning Register Setup',
    type: 'DWS',
    category: 'POS Operations',
    estimatedMinutes: 60,
    description: 'Set up cash registers and prepare POS systems for daily operations. Check cash float, printer paper, and system connectivity.',
    manualGuide: '1.1.1',
    manualLink: 'https://manual.aeon.vn/pos/1.1.1',
    priority: 'High',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 1,
  },
  {
    id: 2,
    code: '1.1.2',
    title: 'Cash Float Verification',
    type: 'DWS',
    category: 'POS Operations',
    estimatedMinutes: 60,
    description: 'Verify starting cash float matches designated amount. Document any discrepancies.',
    manualGuide: '1.1.2',
    manualLink: 'https://manual.aeon.vn/pos/1.1.2',
    priority: 'High',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 2,
  },
  {
    id: 3,
    code: '1.1.3',
    title: 'POS System Login',
    type: 'DWS',
    category: 'POS Operations',
    estimatedMinutes: 60,
    description: 'Log into all POS terminals and verify system functionality.',
    manualGuide: '1.1.3',
    manualLink: 'https://manual.aeon.vn/pos/1.1.3',
    priority: 'High',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 3,
  },
  {
    id: 4,
    code: '1.2.1',
    title: 'End of Day Cash Reconciliation',
    type: 'DWS',
    category: 'POS Operations',
    estimatedMinutes: 60,
    description: 'Reconcile cash drawers at end of day. Count cash and verify against system records.',
    manualGuide: '1.2.1',
    manualLink: 'https://manual.aeon.vn/pos/1.2.1',
    priority: 'High',
    timeOfDay: 'Evening',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 4,
  },

  // Inventory Management (22 tasks)
  {
    id: 5,
    code: '2.1.1',
    title: 'Inventory Count - Freezer Section',
    type: 'DWS',
    category: 'Inventory Management',
    estimatedMinutes: 60,
    description: 'Complete inventory count for all freezer items. Update system with actual counts.',
    manualGuide: '2.1.1',
    manualLink: 'https://manual.aeon.vn/inventory/2.1.1',
    priority: 'High',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 5,
  },
  {
    id: 6,
    code: '2.1.2',
    title: 'Stock Rotation - Perishables',
    type: 'DWS',
    category: 'Inventory Management',
    estimatedMinutes: 60,
    description: 'Rotate stock following FIFO method. Check expiry dates and remove expired items.',
    manualGuide: '2.1.2',
    manualLink: 'https://manual.aeon.vn/inventory/2.1.2',
    priority: 'High',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 6,
  },
  {
    id: 7,
    code: '2.2.1',
    title: 'Receiving Deliveries',
    type: 'DWS',
    category: 'Inventory Management',
    estimatedMinutes: 90,
    description: 'Check delivery against purchase orders. Inspect quality and update inventory.',
    manualGuide: '2.2.1',
    manualLink: 'https://manual.aeon.vn/inventory/2.2.1',
    priority: 'Medium',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 7,
  },

  // Customer Service (15 tasks)
  {
    id: 8,
    code: '3.1.1',
    title: 'Customer Service Desk Coverage',
    type: 'DWS',
    category: 'Customer Service',
    estimatedMinutes: 120,
    description: 'Provide customer support at service desk for inquiries, returns, and complaints.',
    manualGuide: '3.1.1',
    manualLink: 'https://manual.aeon.vn/customer/3.1.1',
    priority: 'Medium',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 8,
  },
  {
    id: 9,
    code: '3.2.1',
    title: 'Handle Customer Returns',
    type: 'DWS',
    category: 'Customer Service',
    estimatedMinutes: 60,
    description: 'Process customer returns according to policy. Verify receipts and condition.',
    manualGuide: '3.2.1',
    manualLink: 'https://manual.aeon.vn/customer/3.2.1',
    priority: 'Medium',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 9,
  },

  // Cleaning & Maintenance (20 tasks)
  {
    id: 10,
    code: '4.1.1',
    title: 'Floor Cleaning - Main Aisle',
    type: 'DWS',
    category: 'Cleaning & Maintenance',
    estimatedMinutes: 60,
    description: 'Clean and sanitize main shopping aisles. Use approved cleaning solutions.',
    manualGuide: '4.1.1',
    manualLink: 'https://manual.aeon.vn/cleaning/4.1.1',
    priority: 'Medium',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 10,
  },
  {
    id: 11,
    code: '4.1.2',
    title: 'Restroom Inspection & Cleaning',
    type: 'DWS',
    category: 'Cleaning & Maintenance',
    estimatedMinutes: 60,
    description: 'Inspect and clean all customer restrooms. Restock supplies.',
    manualGuide: '4.1.2',
    manualLink: 'https://manual.aeon.vn/cleaning/4.1.2',
    priority: 'High',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 11,
  },
  {
    id: 12,
    code: '4.2.1',
    title: 'Entrance Area Cleaning',
    type: 'DWS',
    category: 'Cleaning & Maintenance',
    estimatedMinutes: 60,
    description: 'Clean entrance doors, mats, and surrounding area.',
    manualGuide: '4.2.1',
    manualLink: 'https://manual.aeon.vn/cleaning/4.2.1',
    priority: 'Medium',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 12,
  },

  // Merchandising (12 tasks)
  {
    id: 13,
    code: '5.1.1',
    title: 'Product Display Arrangement',
    type: 'DWS',
    category: 'Merchandising',
    estimatedMinutes: 90,
    description: 'Arrange product displays according to planogram. Ensure proper facing.',
    manualGuide: '5.1.1',
    manualLink: 'https://manual.aeon.vn/merchandising/5.1.1',
    priority: 'Low',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 13,
  },
  {
    id: 14,
    code: '5.2.1',
    title: 'Shelf Stocking',
    type: 'DWS',
    category: 'Merchandising',
    estimatedMinutes: 120,
    description: 'Stock shelves from backroom inventory. Maintain proper product placement.',
    manualGuide: '5.2.1',
    manualLink: 'https://manual.aeon.vn/merchandising/5.2.1',
    priority: 'Medium',
    timeOfDay: 'Afternoon',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 14,
  },

  // Safety & Security (14 tasks)
  {
    id: 15,
    code: '6.1.1',
    title: 'Emergency Exit Check',
    type: 'DWS',
    category: 'Safety & Security',
    estimatedMinutes: 60,
    description: 'Verify all emergency exits are clear and functional.',
    manualGuide: '6.1.1',
    manualLink: 'https://manual.aeon.vn/safety/6.1.1',
    priority: 'High',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 15,
  },
  {
    id: 16,
    code: '6.2.1',
    title: 'Security Camera Review',
    type: 'DWS',
    category: 'Safety & Security',
    estimatedMinutes: 60,
    description: 'Review security camera footage and check system functionality.',
    manualGuide: '6.2.1',
    manualLink: 'https://manual.aeon.vn/safety/6.2.1',
    priority: 'Medium',
    timeOfDay: 'Evening',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 16,
  },

  // Administrative (9 tasks)
  {
    id: 17,
    code: '7.1.1',
    title: 'Staff Attendance Recording',
    type: 'DWS',
    category: 'Administrative',
    estimatedMinutes: 60,
    description: 'Record staff attendance and verify against schedule.',
    manualGuide: '7.1.1',
    manualLink: 'https://manual.aeon.vn/admin/7.1.1',
    priority: 'High',
    timeOfDay: 'Morning',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 17,
  },
  {
    id: 18,
    code: '7.2.1',
    title: 'Daily Sales Report',
    type: 'DWS',
    category: 'Administrative',
    estimatedMinutes: 60,
    description: 'Compile and submit daily sales report to HQ.',
    manualGuide: '7.2.1',
    manualLink: 'https://manual.aeon.vn/admin/7.2.1',
    priority: 'High',
    timeOfDay: 'Evening',
    recurrence: 'daily',
    requiresHQApproval: false,
    isActive: true,
    order: 18,
  },

  // Additional POS Tasks (19-30)
  { id: 19, code: '1.3.1', title: 'Receipt Paper Replacement', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Check and replace receipt paper in all POS terminals.', manualGuide: '1.3.1', manualLink: 'https://manual.aeon.vn/pos/1.3.1', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 19 },
  { id: 20, code: '1.3.2', title: 'POS Terminal Cleaning', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Clean and sanitize all POS terminals.', manualGuide: '1.3.2', manualLink: 'https://manual.aeon.vn/pos/1.3.2', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 20 },
  { id: 21, code: '1.4.1', title: 'Card Reader Testing', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Test all card readers for functionality.', manualGuide: '1.4.1', manualLink: 'https://manual.aeon.vn/pos/1.4.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 21 },
  { id: 22, code: '1.4.2', title: 'Barcode Scanner Check', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Verify all barcode scanners are working properly.', manualGuide: '1.4.2', manualLink: 'https://manual.aeon.vn/pos/1.4.2', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 22 },
  { id: 23, code: '1.5.1', title: 'Cash Drop Procedure', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Perform mid-day cash drops to safe.', manualGuide: '1.5.1', manualLink: 'https://manual.aeon.vn/pos/1.5.1', priority: 'High', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 23 },
  { id: 24, code: '1.5.2', title: 'Change Fund Request', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Request additional change funds as needed.', manualGuide: '1.5.2', manualLink: 'https://manual.aeon.vn/pos/1.5.2', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 24 },
  { id: 25, code: '1.6.1', title: 'Void Transaction Review', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Review and document all void transactions.', manualGuide: '1.6.1', manualLink: 'https://manual.aeon.vn/pos/1.6.1', priority: 'High', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 25 },
  { id: 26, code: '1.6.2', title: 'Return Transaction Log', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Log all return transactions and verify receipts.', manualGuide: '1.6.2', manualLink: 'https://manual.aeon.vn/pos/1.6.2', priority: 'Medium', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 26 },
  { id: 27, code: '1.7.1', title: 'Gift Card Activation', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Activate and stock gift cards.', manualGuide: '1.7.1', manualLink: 'https://manual.aeon.vn/pos/1.7.1', priority: 'Low', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 27 },
  { id: 28, code: '1.7.2', title: 'Loyalty Card Registration', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Process loyalty card registrations.', manualGuide: '1.7.2', manualLink: 'https://manual.aeon.vn/pos/1.7.2', priority: 'Medium', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 28 },
  { id: 29, code: '1.8.1', title: 'Coupon Validation', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Validate and process all coupons.', manualGuide: '1.8.1', manualLink: 'https://manual.aeon.vn/pos/1.8.1', priority: 'Medium', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 29 },
  { id: 30, code: '1.8.2', title: 'Payment Terminal Shutdown', type: 'DWS', category: 'POS Operations', estimatedMinutes: 60, description: 'Properly shut down all payment terminals.', manualGuide: '1.8.2', manualLink: 'https://manual.aeon.vn/pos/1.8.2', priority: 'High', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 30 },

  // Additional Inventory Tasks (31-50)
  { id: 31, code: '2.3.1', title: 'Stock Level Check - Grocery', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Check stock levels in grocery section.', manualGuide: '2.3.1', manualLink: 'https://manual.aeon.vn/inventory/2.3.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 31 },
  { id: 32, code: '2.3.2', title: 'Stock Level Check - Electronics', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Check stock levels in electronics section.', manualGuide: '2.3.2', manualLink: 'https://manual.aeon.vn/inventory/2.3.2', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 32 },
  { id: 33, code: '2.3.3', title: 'Stock Level Check - Clothing', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Check stock levels in clothing section.', manualGuide: '2.3.3', manualLink: 'https://manual.aeon.vn/inventory/2.3.3', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 33 },
  { id: 34, code: '2.4.1', title: 'Receiving - Morning Delivery', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Process morning deliveries and verify shipments.', manualGuide: '2.4.1', manualLink: 'https://manual.aeon.vn/inventory/2.4.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 34 },
  { id: 35, code: '2.4.2', title: 'Receiving - Afternoon Delivery', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Process afternoon deliveries and verify shipments.', manualGuide: '2.4.2', manualLink: 'https://manual.aeon.vn/inventory/2.4.2', priority: 'High', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 35 },
  { id: 36, code: '2.5.1', title: 'Backroom Organization', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Organize backroom storage areas.', manualGuide: '2.5.1', manualLink: 'https://manual.aeon.vn/inventory/2.5.1', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 36 },
  { id: 37, code: '2.5.2', title: 'Pallet Wrap and Storage', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Wrap and properly store pallets.', manualGuide: '2.5.2', manualLink: 'https://manual.aeon.vn/inventory/2.5.2', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 37 },
  { id: 38, code: '2.6.1', title: 'Damaged Goods Report', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Document and report damaged merchandise.', manualGuide: '2.6.1', manualLink: 'https://manual.aeon.vn/inventory/2.6.1', priority: 'High', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 38 },
  { id: 39, code: '2.6.2', title: 'Shrinkage Documentation', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Record shrinkage and missing inventory.', manualGuide: '2.6.2', manualLink: 'https://manual.aeon.vn/inventory/2.6.2', priority: 'High', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 39 },
  { id: 40, code: '2.7.1', title: 'Restock - Dairy Products', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Restock dairy products from cooler.', manualGuide: '2.7.1', manualLink: 'https://manual.aeon.vn/inventory/2.7.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 40 },
  { id: 41, code: '2.7.2', title: 'Restock - Frozen Foods', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Restock frozen food section.', manualGuide: '2.7.2', manualLink: 'https://manual.aeon.vn/inventory/2.7.2', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 41 },
  { id: 42, code: '2.7.3', title: 'Restock - Produce', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Restock produce section.', manualGuide: '2.7.3', manualLink: 'https://manual.aeon.vn/inventory/2.7.3', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 42 },
  { id: 43, code: '2.8.1', title: 'Expiry Date Check - Dairy', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Check expiry dates on dairy products.', manualGuide: '2.8.1', manualLink: 'https://manual.aeon.vn/inventory/2.8.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 43 },
  { id: 44, code: '2.8.2', title: 'Expiry Date Check - Bakery', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Check expiry dates on bakery items.', manualGuide: '2.8.2', manualLink: 'https://manual.aeon.vn/inventory/2.8.2', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 44 },
  { id: 45, code: '2.9.1', title: 'Price Label Verification - Grocery', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Verify price labels in grocery section.', manualGuide: '2.9.1', manualLink: 'https://manual.aeon.vn/inventory/2.9.1', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 45 },
  { id: 46, code: '2.9.2', title: 'Price Label Verification - Non-food', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Verify price labels in non-food section.', manualGuide: '2.9.2', manualLink: 'https://manual.aeon.vn/inventory/2.9.2', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 46 },
  { id: 47, code: '2.10.1', title: 'Bin Location Update', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Update bin locations in system.', manualGuide: '2.10.1', manualLink: 'https://manual.aeon.vn/inventory/2.10.1', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 47 },
  { id: 48, code: '2.10.2', title: 'Stock Transfer Processing', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Process stock transfers between locations.', manualGuide: '2.10.2', manualLink: 'https://manual.aeon.vn/inventory/2.10.2', priority: 'High', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 48 },
  { id: 49, code: '2.11.1', title: 'Cycle Count - Section A', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Perform cycle count in designated section.', manualGuide: '2.11.1', manualLink: 'https://manual.aeon.vn/inventory/2.11.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 49 },
  { id: 50, code: '2.11.2', title: 'Inventory Adjustment Entry', type: 'DWS', category: 'Inventory', estimatedMinutes: 60, description: 'Enter inventory adjustments into system.', manualGuide: '2.11.2', manualLink: 'https://manual.aeon.vn/inventory/2.11.2', priority: 'High', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 50 },

  // Customer Service Tasks (51-65)
  { id: 51, code: '3.3.1', title: 'Customer Queue Management', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Monitor and manage customer queue times.', manualGuide: '3.3.1', manualLink: 'https://manual.aeon.vn/service/3.3.1', priority: 'High', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 51 },
  { id: 52, code: '3.3.2', title: 'Customer Complaint Log', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Log and process customer complaints.', manualGuide: '3.3.2', manualLink: 'https://manual.aeon.vn/service/3.3.2', priority: 'High', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 52 },
  { id: 53, code: '3.4.1', title: 'Shopping Cart Collection', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Collect shopping carts from parking lot.', manualGuide: '3.4.1', manualLink: 'https://manual.aeon.vn/service/3.4.1', priority: 'Medium', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 53 },
  { id: 54, code: '3.4.2', title: 'Shopping Basket Cleaning', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Clean and sanitize shopping baskets.', manualGuide: '3.4.2', manualLink: 'https://manual.aeon.vn/service/3.4.2', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 54 },
  { id: 55, code: '3.5.1', title: 'Product Information Assistance', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Assist customers with product information.', manualGuide: '3.5.1', manualLink: 'https://manual.aeon.vn/service/3.5.1', priority: 'High', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 55 },
  { id: 56, code: '3.5.2', title: 'Special Order Processing', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Process special customer orders.', manualGuide: '3.5.2', manualLink: 'https://manual.aeon.vn/service/3.5.2', priority: 'Medium', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 56 },
  { id: 57, code: '3.6.1', title: 'Lost and Found Management', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Manage lost and found items.', manualGuide: '3.6.1', manualLink: 'https://manual.aeon.vn/service/3.6.1', priority: 'Low', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 57 },
  { id: 58, code: '3.6.2', title: 'Customer Feedback Collection', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Collect and document customer feedback.', manualGuide: '3.6.2', manualLink: 'https://manual.aeon.vn/service/3.6.2', priority: 'Medium', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 58 },
  { id: 59, code: '3.7.1', title: 'Fitting Room Check', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Check and clean fitting rooms.', manualGuide: '3.7.1', manualLink: 'https://manual.aeon.vn/service/3.7.1', priority: 'Medium', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 59 },
  { id: 60, code: '3.7.2', title: 'Return/Exchange Processing', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Process customer returns and exchanges.', manualGuide: '3.7.2', manualLink: 'https://manual.aeon.vn/service/3.7.2', priority: 'High', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 60 },
  { id: 61, code: '3.8.1', title: 'Price Check Assistance', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Assist customers with price checks.', manualGuide: '3.8.1', manualLink: 'https://manual.aeon.vn/service/3.8.1', priority: 'Medium', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 61 },
  { id: 62, code: '3.8.2', title: 'Carry-out Assistance', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Assist customers with carry-out service.', manualGuide: '3.8.2', manualLink: 'https://manual.aeon.vn/service/3.8.2', priority: 'Medium', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 62 },
  { id: 63, code: '3.9.1', title: 'Phone Inquiry Handling', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Handle customer phone inquiries.', manualGuide: '3.9.1', manualLink: 'https://manual.aeon.vn/service/3.9.1', priority: 'Medium', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 63 },
  { id: 64, code: '3.9.2', title: 'Online Order Pickup Prep', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Prepare online orders for customer pickup.', manualGuide: '3.9.2', manualLink: 'https://manual.aeon.vn/service/3.9.2', priority: 'High', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 64 },
  { id: 65, code: '3.10.1', title: 'Customer Survey Distribution', type: 'DWS', category: 'Customer Service', estimatedMinutes: 60, description: 'Distribute customer satisfaction surveys.', manualGuide: '3.10.1', manualLink: 'https://manual.aeon.vn/service/3.10.1', priority: 'Low', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 65 },

  // Cleaning & Maintenance Tasks (66-85)
  { id: 66, code: '4.3.1', title: 'Entrance Door Cleaning', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Clean entrance doors and handles.', manualGuide: '4.3.1', manualLink: 'https://manual.aeon.vn/cleaning/4.3.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 66 },
  { id: 67, code: '4.3.2', title: 'Checkout Counter Cleaning', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Clean and sanitize checkout counters.', manualGuide: '4.3.2', manualLink: 'https://manual.aeon.vn/cleaning/4.3.2', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 67 },
  { id: 68, code: '4.4.1', title: 'Restroom Check - Morning', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Morning restroom inspection and cleaning.', manualGuide: '4.4.1', manualLink: 'https://manual.aeon.vn/cleaning/4.4.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 68 },
  { id: 69, code: '4.4.2', title: 'Restroom Check - Midday', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Midday restroom inspection and cleaning.', manualGuide: '4.4.2', manualLink: 'https://manual.aeon.vn/cleaning/4.4.2', priority: 'High', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 69 },
  { id: 70, code: '4.4.3', title: 'Restroom Check - Evening', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Evening restroom inspection and cleaning.', manualGuide: '4.4.3', manualLink: 'https://manual.aeon.vn/cleaning/4.4.3', priority: 'High', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 70 },
  { id: 71, code: '4.5.1', title: 'Break Room Cleaning', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Clean staff break room and kitchen.', manualGuide: '4.5.1', manualLink: 'https://manual.aeon.vn/cleaning/4.5.1', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 71 },
  { id: 72, code: '4.5.2', title: 'Office Area Cleaning', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Clean office areas and workstations.', manualGuide: '4.5.2', manualLink: 'https://manual.aeon.vn/cleaning/4.5.2', priority: 'Medium', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 72 },
  { id: 73, code: '4.6.1', title: 'Window Cleaning - Interior', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Clean interior windows and glass.', manualGuide: '4.6.1', manualLink: 'https://manual.aeon.vn/cleaning/4.6.1', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 73 },
  { id: 74, code: '4.6.2', title: 'Mirror Cleaning', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Clean all mirrors throughout store.', manualGuide: '4.6.2', manualLink: 'https://manual.aeon.vn/cleaning/4.6.2', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 74 },
  { id: 75, code: '4.7.1', title: 'Aisle Floor Sweeping', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Sweep all sales floor aisles.', manualGuide: '4.7.1', manualLink: 'https://manual.aeon.vn/cleaning/4.7.1', priority: 'High', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 75 },
  { id: 76, code: '4.7.2', title: 'Aisle Floor Mopping', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Mop all sales floor aisles.', manualGuide: '4.7.2', manualLink: 'https://manual.aeon.vn/cleaning/4.7.2', priority: 'High', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 76 },
  { id: 77, code: '4.8.1', title: 'Spill Station Check', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Check spill cleanup stations are stocked.', manualGuide: '4.8.1', manualLink: 'https://manual.aeon.vn/cleaning/4.8.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 77 },
  { id: 78, code: '4.8.2', title: 'Trash Collection - Sales Floor', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Collect trash from sales floor bins.', manualGuide: '4.8.2', manualLink: 'https://manual.aeon.vn/cleaning/4.8.2', priority: 'High', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 78 },
  { id: 79, code: '4.8.3', title: 'Trash Collection - Backroom', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Collect trash from backroom areas.', manualGuide: '4.8.3', manualLink: 'https://manual.aeon.vn/cleaning/4.8.3', priority: 'Medium', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 79 },
  { id: 80, code: '4.9.1', title: 'Cardboard Baling', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Bale and prepare cardboard for recycling.', manualGuide: '4.9.1', manualLink: 'https://manual.aeon.vn/cleaning/4.9.1', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 80 },
  { id: 81, code: '4.9.2', title: 'Recycling Station Management', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Manage recycling stations.', manualGuide: '4.9.2', manualLink: 'https://manual.aeon.vn/cleaning/4.9.2', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 81 },
  { id: 82, code: '4.10.1', title: 'Equipment Cleaning - Carts', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Clean store equipment and carts.', manualGuide: '4.10.1', manualLink: 'https://manual.aeon.vn/cleaning/4.10.1', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 82 },
  { id: 83, code: '4.10.2', title: 'Display Fixture Dusting', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Dust display fixtures and shelving.', manualGuide: '4.10.2', manualLink: 'https://manual.aeon.vn/cleaning/4.10.2', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 83 },
  { id: 84, code: '4.11.1', title: 'Parking Lot Sweep', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Sweep parking lot and entrance areas.', manualGuide: '4.11.1', manualLink: 'https://manual.aeon.vn/cleaning/4.11.1', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 84 },
  { id: 85, code: '4.11.2', title: 'Exterior Trash Collection', type: 'DWS', category: 'Cleaning', estimatedMinutes: 60, description: 'Collect trash from exterior bins.', manualGuide: '4.11.2', manualLink: 'https://manual.aeon.vn/cleaning/4.11.2', priority: 'Medium', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 85 },

  // Merchandising Tasks (86-100)
  { id: 86, code: '5.3.1', title: 'Endcap Display Setup', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Set up endcap promotional displays.', manualGuide: '5.3.1', manualLink: 'https://manual.aeon.vn/merch/5.3.1', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 86 },
  { id: 87, code: '5.3.2', title: 'Planogram Compliance Check', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Verify planogram compliance.', manualGuide: '5.3.2', manualLink: 'https://manual.aeon.vn/merch/5.3.2', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 87 },
  { id: 88, code: '5.4.1', title: 'Product Facing - Grocery', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Face and organize grocery products.', manualGuide: '5.4.1', manualLink: 'https://manual.aeon.vn/merch/5.4.1', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 88 },
  { id: 89, code: '5.4.2', title: 'Product Facing - Non-food', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Face and organize non-food products.', manualGuide: '5.4.2', manualLink: 'https://manual.aeon.vn/merch/5.4.2', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 89 },
  { id: 90, code: '5.5.1', title: 'Promotional Signage Setup', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Install promotional signage.', manualGuide: '5.5.1', manualLink: 'https://manual.aeon.vn/merch/5.5.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 90 },
  { id: 91, code: '5.5.2', title: 'Price Sign Verification', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Verify all price signs are correct.', manualGuide: '5.5.2', manualLink: 'https://manual.aeon.vn/merch/5.5.2', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 91 },
  { id: 92, code: '5.6.1', title: 'Cross-Merchandising Setup', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Set up cross-merchandising displays.', manualGuide: '5.6.1', manualLink: 'https://manual.aeon.vn/merch/5.6.1', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 92 },
  { id: 93, code: '5.6.2', title: 'Impulse Buy Station Check', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Check and restock impulse buy areas.', manualGuide: '5.6.2', manualLink: 'https://manual.aeon.vn/merch/5.6.2', priority: 'Medium', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 93 },
  { id: 94, code: '5.7.1', title: 'Window Display Update', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Update window displays.', manualGuide: '5.7.1', manualLink: 'https://manual.aeon.vn/merch/5.7.1', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 94 },
  { id: 95, code: '5.7.2', title: 'Feature Table Arrangement', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Arrange feature product tables.', manualGuide: '5.7.2', manualLink: 'https://manual.aeon.vn/merch/5.7.2', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 95 },
  { id: 96, code: '5.8.1', title: 'Clearance Section Organization', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Organize clearance section.', manualGuide: '5.8.1', manualLink: 'https://manual.aeon.vn/merch/5.8.1', priority: 'Low', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 96 },
  { id: 97, code: '5.8.2', title: 'Sale Item Flagging', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Flag and highlight sale items.', manualGuide: '5.8.2', manualLink: 'https://manual.aeon.vn/merch/5.8.2', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 97 },
  { id: 98, code: '5.9.1', title: 'Product Sample Station Setup', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Set up product sampling stations.', manualGuide: '5.9.1', manualLink: 'https://manual.aeon.vn/merch/5.9.1', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 98 },
  { id: 99, code: '5.9.2', title: 'Mannequin Dressing', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Dress mannequins with new merchandise.', manualGuide: '5.9.2', manualLink: 'https://manual.aeon.vn/merch/5.9.2', priority: 'Low', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 99 },
  { id: 100, code: '5.10.1', title: 'Seasonal Display Rotation', type: 'DWS', category: 'Merchandising', estimatedMinutes: 60, description: 'Rotate seasonal display merchandise.', manualGuide: '5.10.1', manualLink: 'https://manual.aeon.vn/merch/5.10.1', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 100 },

  // Additional Safety & Admin Tasks (101-110)
  { id: 101, code: '6.3.1', title: 'First Aid Kit Check', type: 'DWS', category: 'Safety & Security', estimatedMinutes: 60, description: 'Check first aid kits are stocked.', manualGuide: '6.3.1', manualLink: 'https://manual.aeon.vn/safety/6.3.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 101 },
  { id: 102, code: '6.3.2', title: 'Fire Extinguisher Inspection', type: 'DWS', category: 'Safety & Security', estimatedMinutes: 60, description: 'Inspect fire extinguisher locations.', manualGuide: '6.3.2', manualLink: 'https://manual.aeon.vn/safety/6.3.2', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 102 },
  { id: 103, code: '6.4.1', title: 'Security Alarm Test', type: 'DWS', category: 'Safety & Security', estimatedMinutes: 60, description: 'Test security alarm systems.', manualGuide: '6.4.1', manualLink: 'https://manual.aeon.vn/safety/6.4.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 103 },
  { id: 104, code: '6.4.2', title: 'Security Tag Deactivator Check', type: 'DWS', category: 'Safety & Security', estimatedMinutes: 60, description: 'Test security tag deactivators.', manualGuide: '6.4.2', manualLink: 'https://manual.aeon.vn/safety/6.4.2', priority: 'Medium', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 104 },
  { id: 105, code: '6.5.1', title: 'Parking Lot Patrol', type: 'DWS', category: 'Safety & Security', estimatedMinutes: 60, description: 'Patrol parking lot for security.', manualGuide: '6.5.1', manualLink: 'https://manual.aeon.vn/safety/6.5.1', priority: 'Medium', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 105 },
  { id: 106, code: '7.3.1', title: 'Staff Schedule Review', type: 'DWS', category: 'Administrative', estimatedMinutes: 60, description: 'Review and post staff schedules.', manualGuide: '7.3.1', manualLink: 'https://manual.aeon.vn/admin/7.3.1', priority: 'High', timeOfDay: 'Morning', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 106 },
  { id: 107, code: '7.3.2', title: 'Break Schedule Coordination', type: 'DWS', category: 'Administrative', estimatedMinutes: 60, description: 'Coordinate staff break schedules.', manualGuide: '7.3.2', manualLink: 'https://manual.aeon.vn/admin/7.3.2', priority: 'High', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 107 },
  { id: 108, code: '7.4.1', title: 'Supply Order Submission', type: 'DWS', category: 'Administrative', estimatedMinutes: 60, description: 'Submit supply orders to HQ.', manualGuide: '7.4.1', manualLink: 'https://manual.aeon.vn/admin/7.4.1', priority: 'Medium', timeOfDay: 'Afternoon', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 108 },
  { id: 109, code: '7.4.2', title: 'Store Communication Log', type: 'DWS', category: 'Administrative', estimatedMinutes: 60, description: 'Log store communications and updates.', manualGuide: '7.4.2', manualLink: 'https://manual.aeon.vn/admin/7.4.2', priority: 'High', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 109 },
  { id: 110, code: '7.5.1', title: 'Store Closing Checklist', type: 'DWS', category: 'Administrative', estimatedMinutes: 60, description: 'Complete store closing procedures.', manualGuide: '7.5.1', manualLink: 'https://manual.aeon.vn/admin/7.5.1', priority: 'High', timeOfDay: 'Evening', recurrence: 'daily', requiresHQApproval: false, isActive: true, order: 110 },
];
